### ISSUE TITLE
How can we use this Auto Tester may you explain it in details?

### ISSUE THREAD

**Issue by ArbitCode** [dush1729/Auto-Tester#2]
I have generated test cases for inbuilt c++ code in repo. but I want to find test cases for my c++ code. how can I use it?

**Comment by dush1729** [comment]
Hi please check sample directory for examples.
Link - https://github.com/dush1729/Auto-Tester/tree/master/sample

Run the script using
python2 test.py -c correct_code.cpp -w wrong_code.cpp -g generator.cpp
then it will try to find testcases on which you correct and wrong output give different result.

Check the README for more details.
